export const PAGE_MESSAGE_TYPES = {
  ELEMENT_ACTION: 'ELEMENT_ACTION',
  CHECK_ELEMENT_VIDEO_SELECTED: 'CHECK_ELEMENT_VIDEO_SELECTED',
  RESULT_CHECK_ELEMENT_VIDEO_SELECTED: 'RESULT_CHECK_ELEMENT_VIDEO_SELECTED',
};
