export const PAGE_MESSAGE_TYPES = {
  ELEMENT_ACTION: 'ELEMENT_ACTION',
  GET_VIDEOS_DATA: 'GET_VIDEOS_DATA',
  RESULT_VIDEOS_DATA: 'RESULT_VIDEOS_DATA',
  GET_TABS: 'GET_TABS',
  RESULT_TABS: 'RESULT_TABS',
  CHECK_ELEMENT_VIDEO_SELECTED: 'CHECK_ELEMENT_VIDEO_SELECTED',
  RESULT_CHECK_ELEMENT_VIDEO_SELECTED: 'RESULT_CHECK_ELEMENT_VIDEO_SELECTED',
  ADD_EVENTS_ELEMENT: 'ADD_EVENTS_ELEMENT',
  GET_VIDEO_INFO: 'GET_VIDEO_INFO',
  RESULT_VIDEO_INFO: 'RESULT_VIDEO_INFO',
};
